---
- name: 'Create timer for MongoDB backup: {{ hackmd_db_backup_service_name }}'
  include_role: name=infra-role-systemd-timer
  vars:
    systemd_timer_name: '{{ hackmd_db_backup_service_name }}'
    systemd_timer_description: 'Dump HackMD PostgreSQL database.'
    systemd_timer_user: '{{ hackmd_db_backup_user }}'
    systemd_timer_frequency: '{{ hackmd_db_backup_frequency }}'
    systemd_timer_timeout_sec: '{{ hackmd_db_backup_timeout }}'
    systemd_timer_after_extra: 'docker.service'
    systemd_timer_start_on_creation: false
    systemd_timer_script_content: |
      #!/usr/bin/env bash
      BKP_DIR="{{ hackmd_db_cont_vol }}/backup/{{ hackmd_db_name }}"
      rm -vfr "${BKP_DIR}"
      /usr/bin/docker exec -i {{ hackmd_db_cont_name }} \
        pg_dump -F directory -f "/backup/{{ hackmd_db_name }}" \
        -U {{ hackmd_db_user }} {{ hackmd_db_name }}
      chmod 750 -R "${BKP_DIR}"
