---
- name: CodiMD | Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ codimd_service_name }}'
    consul_services:
      - name: '{{ codimd_service_name }}'
        tags: ['codimd', 'notes', 'misc']
        # we advertise the port with basic auth
        port: '{{ codimd_app_cont_port }}'
        checks:
          - id: '{{ codimd_service_name }}-status'
            name: CodiMD Healthcheck
            type: http
            http: 'http://localhost:{{ codimd_app_cont_port }}/config'
