---
- name: CodiMD | Configure nginx proxy
  include_role: name=infra-role-nginx
  vars:
    nginx_configs:
      codimd_rate_limiting:
        # Limit requests to 40 per minute based on IP
        - limit_req_zone $binary_remote_addr zone=codimd_by_ip:20m rate=40r/m
    nginx_sites:
      codimd_http:
        - listen 80
        - server_name {{ codimd_domain }}
        - return 301 https://{{ codimd_domain }}$request_uri

      codimd_ssl:
        - listen 443 ssl
        - server_name {{ codimd_domain }}

        - ssl_certificate     /certs/origin.crt
        - ssl_certificate_key /certs/origin.key

        - proxy_set_header X-Frame-Options sameorigin

        # Script kiddies like scanning paths, so we rate limit most.
        - location / {
            limit_req zone=codimd_by_ip burst=30 nodelay;
            proxy_pass http://localhost:{{ codimd_app_cont_port }}/;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_redirect off;
          }

        # This path is used when editing so we can't rate limit it easily.
        - location ~ ^/(socket.io|config|me) {
            proxy_pass http://localhost:{{ codimd_app_cont_port }};
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_redirect off;
          }
